---
- name: add nodejs key.
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  become: yes

- name: update NodeJS Source List.
  apt_repository:
    repo: deb https://deb.nodesource.com/node_12.x bionic main
    filename: nodesource
    update_cache: yes
    state: present
  become: yes

- name: Installing required packages.
  apt:
    pkg: "{{packages}}"
    state: present
  become: yes

- name: apt update.
  apt:
    update_cache: false
  become: yes

- name: Copy package-lock files
  become: yes
  copy:
    src: package-lock.json
    dest: package-lock.json

- name: Copy package files
  become: yes
  copy:
    src: package.json
    dest: package.json

- name: Install package files
  command: npm install -g
  args:
    chdir: /root
  become: yes

- name: Install Forever.
  npm:
    name: forever
    global: yes
  become: yes