---
- name: Clone checkbox.io repo on blue
  git:
    repo: https://github.com/chrisparnin/checkbox.io-micro-preview.git
    dest: /home/vagrant/checkbox.io-micro-preview
    version: "{{ blue }}"
  when: inventory_hostname == "192.168.44.25"
  become: yes

- name: Clone checkbox.io repo on green
  git:
    repo: https://github.com/chrisparnin/checkbox.io-micro-preview.git
    dest: /home/vagrant/checkbox.io-micro-preview
    version: "{{ green }}"
  when: inventory_hostname == "192.168.44.30"
  become: yes

- name: Install checkbox.io-micro-preview
  npm:
    path: /home/vagrant/checkbox.io-micro-preview
  become: yes

- name: Delete all  PM2 process
  command: pm2 delete all
  ignore_errors: True

- name: Start checkbox.io as PM2 process
  command: pm2 start index.js
  args:
    chdir: /home/vagrant/checkbox.io-micro-preview

- name: "Check list of Node.js apps running."
  command: forever stopall
  register: forever_list

- name: "Start agent on blue"
  command: forever start /bakerx/cm/canary-analysis/proxy/agent/index.js blue
  when: inventory_hostname == "192.168.44.25"

- name: "Start agenton green"
  command: forever start /bakerx/cm/canary-analysis/proxy/agent/index.js green
  when: inventory_hostname == "192.168.44.30"