---
    - name: add jenkins-job-builder
      apt:
        name: jenkins-job-builder
        state: latest
      become: yes

    - name: add jq
      apt:
        name: jq
        state: latest
      become: yes

    - name: populate /etc/environment
      lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value}}"
      with_items: "{{ os_environment }}"
      become: yes

    - name: add jenkins user to sudoers file
      lineinfile:
        dest: /etc/sudoers
        state: present
        insertafter: "^%sudo   ALL="
        line: "jenkins ALL=(ALL) NOPASSWD: ALL"
      become: yes