---
#     - name: add jenkins-job-builder
#       apt:
#         name: jenkins-job-builder
#         state: latest
#       become: yes

#     - name: add jq
#       apt:
#         name: jq
#         state: latest
#       become: yes

    - name: add jenkins user to sudoers file
      lineinfile:
        dest: /etc/sudoers
        state: present
        insertbefore: "# See sudoers"
        line: "jenkins ALL=(ALL) NOPASSWD: ALL"
      become: yes

    - name: Add the user 'jenkins' to group of 'vagrant'
      user:
        name: jenkins
        groups: root,vagrant
        append: yes
      become: yes

    - name: populate environment variables
      lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value}}"
      with_items: "{{ os_environment }}"
      become: true
    # - name: Get home path
    #   shell: echo ~
    #   register: Home_val
    
    # - name: populate environment variables
    #   lineinfile:
    #     dest: "{{ Home_val.stdout }}/.bashrc"
    #     line: "export MONGO_IP=localhost"
    #     insertbefore: BOF
    #   become: yes

    # - name: populate environment variables
    #   lineinfile:
    #     dest: "{{ Home_val.stdout }}/.bashrc"
    #     line: "export APP_PORT=3002"
    #     insertbefore: BOF
    #   become: yes

    # - name: populate environment variables
    #   lineinfile:
    #     dest: "{{ Home_val.stdout }}/.bashrc"
    #     line: "export MONGO_PORT=27017"
    #     insertbefore: BOF
    #   become: yes

    # - name: populate environment variables
    #   lineinfile:
    #     dest: "{{ Home_val.stdout }}/.bashrc"
    #     line: "export MONGO_USER=mongodb_admin_user"
    #     insertbefore: BOF
    #   become: yes
  
    # - name: populate environment variables
    #   lineinfile:
    #     dest: "{{ Home_val.stdout }}/.bashrc"
    #     line: "export MONGO_PASSWORD={{ default_user_pwd }}"
    #     insertbefore: BOF
    #   become: yes
