---
- name: copy .my.cnf file with mysql root password credentials  
  template: 
    src: my.cnf
    dest: '{{ ansible_env.HOME}}/.my.cnf'
    mode: 0644 
  become: yes

- name: Create database user iTrust_dev with all database privileges
  mysql_user:
    login_user: root
    login_password: root
    name: iTrust_dev
    host: '%'
    password: 12345
    priv: '*.*:ALL'
    state: present      
  become: yes

- name: restart mysql
  service:
    name: mysql
    state: restarted
  become: yes