---
- name: Installing required packages.
  apt:
    pkg: "{{packages}}"
    state: present
  become: yes
  register: result
  until: result.failed == false
  delay: 10
  retries: 15

- name: Copy private key js_rsa
  become: yes
  copy:
    src: ~/.ssh/js_rsa
    dest: /home/vagrant/.ssh/js_rsa
    mode: 0700
    owner: vagrant
    group: vagrant

- name: Copy Redis Config
  become: yes
  copy:
    src: redis.conf
    dest: /etc/redis/redis.conf

- name: Restart Redis server
  systemd:
    state: restarted
    daemon_reload: yes
    name: redis
    enabled: yes
  become: yes

- name: Install global packages
  command: npm install --no-bin-links
  args:
    chdir: /bakerx/cm/canary-analysis/proxy
  become: yes

- name: Install global packages
  command: npm install --no-bin-links
  args:
    chdir: /bakerx/cm/canary-analysis/proxy/servers
  become: yes

- name: Clone checkbox.io repo
  git:
    repo: https://github.com/chrisparnin/checkbox.io-micro-preview.git
    dest: /home/vagrant/checkbox.io-micro-preview
  become: yes