---
- name: Copy package-lock files
  become: yes
  copy:
    src: package-lock.json
    dest: package-lock.json

- name: Copy package files
  become: yes
  copy:
    src: package.json
    dest: package.json

- name: Install package files
  npm:
    path: /root

- name: Install Forever.
  npm:
    name: forever
    global: yes
  become: yes