---
- name: populate environment variables.
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ os_environment }}"
  become: yes

- name: apt update.
  apt:
    update_cache: yes
  become: yes

- name: Install PM2.
  npm:
    name: pm2
    global: yes
  become: yes

- name: Install Forever.
  npm:
    name: forever
    global: yes
  become: yes

- name: Install agent packages
  command: npm install --no-bin-links
  args:
    chdir: /bakerx/cm/canary-analysis/proxy/agent
  become: yes