- name: Create initialization scripts directory
  become: yes
  file: path=/var/lib/jenkins/init.groovy.d
        state=directory
        mode=0775

- name: Add initialization script to setup basic security
  become: yes
  template: src=basic-security.groovy
            dest=/var/lib/jenkins/init.groovy.d/basic-security.groovy

- name: Set Jenkins server port to 9000.
  become: yes
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^HTTP_PORT='
    line: HTTP_PORT=9000

- name: Restart Jenkins if required
  service:
    name: jenkins
    state: restarted
  become: yes

- name: Turnoff Jenkins setup wizard.
  become: yes
  lineinfile:
    dest: /etc/default/jenkins
    regexp: '^JAVA_ARGS='
    line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'

- name: Restart Jenkins if required
  service:
    name: jenkins
    state: restarted
  become: yes

- name: Wait for Jenkins to start up
  uri:
    url: http://192.168.33.20:9000
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200

- name: Install build-pipeline-plugin.
  jenkins_plugin:
    name: build-pipeline-plugin
    with_dependencies: yes
    state: latest
    url: http://192.168.33.20:9000
    url_username: admin
    url_password: "{{ jenkins_default_pwd }}"

- name: Restart Jenkins if required
  service:
    name: jenkins
    state: restarted
  become: yes

- name: Wait for Jenkins to start up
  uri:
    url: http://192.168.33.20:9000
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200

- name: Install workflow-aggregator plugin.
  jenkins_plugin:
    name: workflow-aggregator
    with_dependencies: yes
    state: latest
    url: http://192.168.33.20:9000
    url_username: admin
    url_password: "{{ jenkins_default_pwd }}"

- name: Restart Jenkins if required
  service:
    name: jenkins
    state: restarted
  become: yes

- name: Wait for Jenkins to start up
  uri:
    url: http://192.168.33.20:9000
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200

- name: Install pipeline-github plugin.
  jenkins_plugin:
    name: pipeline-github
    with_dependencies: yes
    state: latest
    url: http://192.168.33.20:9000
    url_username: admin
    url_password: "{{ jenkins_default_pwd }}"

- name: Restart Jenkins if required
  service:
    name: jenkins
    state: restarted
  become: yes
