- name: Set Jenkins server port to 9000.
  become: yes
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^HTTP_PORT='
    line: HTTP_PORT=9000

- name: Restart Jenkins server.
  become: yes
  command: service jenkins restart